- name: Deploy app to kind
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create kind cluster
      command: kind create cluster --name molecule
      ignore_errors: true

    - name: Set kubeconfig
      shell: kind get kubeconfig --name molecule > ~/.kube/config

    - name: Deploy Kubernetes manifests
      command: kubectl apply -f ../../../k8s