driver:
  name: default

platforms:
  - name: localhost
    groups:
      - local
    children: []

scenario:
  test_sequence:
    - dependency
    - converge
    - verify

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local

verifier:
  name: ansible